"""initial

Revision ID: 30aa24f7f925
Revises: 673fcee65612
Create Date: 2026-08-13 17:34:50.808629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '30aa24f7f925'
down_revision: Union[str, Sequence[str], None] = '673fcee65612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playerevent')
    op.drop_table('searchevent')
    op.drop_table('memoryresponse')
    op.drop_table('requestd')
    with op.batch_alter_table('owner_platform_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_cycle', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('amount_per_period', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_platform_subscription', schema=None) as batch_op:
        batch_op.drop_column('amount_per_period')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('billing_cycle')

    op.create_table('requestd',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoryresponse',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('response_status', sa.VARCHAR(), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('desicion', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
