"""initial

Revision ID: 673fcee65612
Revises: c24db3aa8a1c
Create Date: 2026-08-13 17:18:17.558337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '673fcee65612'
down_revision: Union[str, Sequence[str], None] = 'c24db3aa8a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playerevent')
    op.drop_table('memoryresponse')
    op.drop_table('requestd')
    op.drop_table('searchevent')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_platform_subscription_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_owner_platform_sub_id', 'owner_platform_subscription', ['owner_platform_subscription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_platform_subscription_id')

    op.create_table('searchevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestd',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoryresponse',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('response_status', sa.VARCHAR(), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('desicion', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
