"""upgrade

Revision ID: 994e7a606d3d
Revises: 92478e74e04d
Create Date: 2026-08-22 00:30:32.120671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '994e7a606d3d'
down_revision: Union[str, Sequence[str], None] = '92478e74e04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestd')
    op.drop_table('searchevent')
    op.drop_table('playerevent')
    op.drop_table('memoryresponse')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('appointment_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('court_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               nullable=True)
        batch_op.create_foreign_key('fk_court_id', 'court', ['court_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.alter_column('session_time',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.alter_column('session_time',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('appointment_owner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('court_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('memoryresponse',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('response_status', sa.VARCHAR(), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('desicion', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestd',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
