"""new upgrade

Revision ID: c24db3aa8a1c
Revises: 
Create Date: 2026-08-10 17:52:56.907263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c24db3aa8a1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playerevent')
    op.drop_table('memoryresponse')
    op.drop_table('requestd')
    op.drop_table('searchevent')
    with op.batch_alter_table('user_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_field', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('searchevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestd',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoryresponse',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('response_status', sa.VARCHAR(), nullable=False),
    sa.Column('team_id', sa.CHAR(length=32), nullable=False),
    sa.Column('req_id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerevent',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('player_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('desicion', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
